name: myapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  provider: ^6.1.2
  go_router: ^17.0.0
  flutter_dotenv: ^6.0.0
  http: ^1.2.1
  firebase_core: ^4.2.1
  firebase_app_check: ^0.4.1+2
  fl_chart: ^1.1.1
  intl: ^0.20.2
  health: ^13.2.1
  pedometer: ^4.0.1
  device_calendar: ^4.3.3
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^5.0.1
  timezone: ^0.9.4
  table_calendar: ^3.1.2
  shared_preferences: ^2.2.3
  chat_gpt_sdk: ^3.1.4
  geocoding: ^4.0.0
  google_maps_flutter: ^2.14.0
  location: ^8.0.1
  permission_handler: ^12.0.1
  flutter_polyline_points: ^3.1.0
  image_picker: ^1.2.0
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.5
  workmanager: ^0.9.0+3
  home_widget: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - packages/timezone/data/latest.tzf
    - assets/images/
